### ISSUE TITLE
update failure

### ISSUE THREAD

**Issue by Batata1021** [TheMulhima/Scarab#131]
### Lumafly Version

v1.14.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

the download just suddenly fails for some reason

### Expected Behaviour

lumafly newest version

### Actual Behaviour

update failed

### Errors and Logs

Lumafly failed to download update automatically. Lumafly will now open the link to get the latest version

Lumafly Version: 3.2.0.0

System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
 ---> System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at NetSparkleUpdater.Downloaders.WebClientFileDownloader.StartFileDownloadAsync(Uri uri, String downloadFilePath)

**Comment by Ruttie2006** [comment]
Hi, this seems like an issue with your internet, is it still happening?
