### ISSUE TITLE
无法下载自己编辑的整合包

### ISSUE THREAD

**Issue by liwy1024** [TheMulhima/Scarab#133]
### Lumafly Version

3.3.0.0

### Hollow Knight Version

1.5.78.11833

### Steps to Reproduce

下载自己编辑的整合包

### Expected Behaviour

成功下载安装自己的整合包

### Actual Behaviour

在没有安装模组的情况下，编辑好自己的整合包后点击加载整合包，在经过漫长的加载时间后显示错误；下载单个模组可以迅速安装，电脑网络无问题，可以正常访问github。

### Errors and Logs

An error occured when activating pack. Lumafly will revert to old mods

Lumafly Version: 3.3.0.0

System.IO.IOException: The response ended prematurely, with at least 84223867 additional bytes expected.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Lumafly.Util.HttpClientExt.DownloadBytesWithProgressAsync(HttpClient self, ISettings settings, Uri uri, IProgress`1 progress, CancellationToken cts) in D:\a\Lumafly\Lumafly\Lumafly\Util\HttpClientExt.cs:line 184
   at Lumafly.Util.HttpClientExt.DownloadBytesWithProgressAsync(HttpClient self, ISettings settings, Uri uri, IProgress`1 progress, CancellationToken cts) in D:\a\Lumafly\Lumafly\Lumafly\Util\HttpClientExt.cs:line 184
   at Lumafly.Services.Installer.DownloadFile(String uri, Action`1 setProgress) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 593
   at Lumafly.Services.Installer._Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 427
   at Lumafly.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable, Boolean clearDlls) in D:\a\Lumafly\Lumafly\Lumafly\Services\Installer.cs:line 369
   at Lumafly.Services.PackManager.LoadPackExclusive(Pack pack) in D:\a\Lumafly\Lumafly\Lumafly\Services\PackManager.cs:line 228

**Comment by Ruttie2006** [comment]
Hi, please use english here, it helps us understand the issue better.
This seems like an issue with your internet, are you still having this issue?
