### ISSUE TITLE
toggle api error

### ISSUE THREAD

**Issue by catocatickitty** [TheMulhima/Scarab#50]
### Scarab Version

2.2.0.0

### Hollow Knight Version

latest version

### Steps to Reproduce

i dont know

### Expected Behaviour

it just didnt toggle the api

### Actual Behaviour

it didnt toggle the api and said there was an error

### Errors and Logs

Scarab Version: 2.2.0.0

System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (github.com:443)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Scarab.Util.HttpClientExt.DownloadBytesWithProgressAsync(HttpClient self, Uri uri, IProgress`1 progress, CancellationToken cts) in D:\a\Scarab\Scarab\Scarab\Util\HttpClientExt.cs:line 22
   at Scarab.Services.Installer.DownloadFile(String uri, Action`1 setProgress) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 467
   at Scarab.Services.Installer._InstallApi(ValueTuple`3 manifest) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 251
   at Scarab.Services.Installer.InstallApi() in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 228
   at Scarab.ViewModels.ModListViewModel.<ToggleApiCommand>g__DoActionWithWithErrorHandling|86_0(Func`1 Action) in D:\a\Scarab\Scarab\Scarab\ViewModels\ModListViewModel.cs:line 477

**Comment by TheMulhima** [comment]
Thanks for the report. It seems like it's just a connection error, try reconnecting your WiFi and try again.

**Comment by TheMulhima** [comment]
Another thing you can do is close scarab, verify integrity of the game via your game vendor (steam/gog), re open scarab and click enable api
