### ISSUE TITLE
Scarab исключает установку модов

### ISSUE THREAD

**Issue by G0l9** [TheMulhima/Scarab#51]
### Scarab Version

v2.2.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Здрваствуйте дорогие разработчики,прошу вас решить найденую мной ошибку и убрать исключение из системы установки,если это возможно.В заранее благодарю за внимание

### Expected Behaviour

Я ожидал легкости установки мода,чтобы поиграть с друзьями.

### Actual Behaviour

Выпала ошибка об исключении установки или удалении мода.

### Errors and Logs

An exception occured while installing or uninstalling Uumuu Plus

Scarab Version: 2.2.0.0

System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Hollow Knight\Hollow Knight_Data\Managed\Assembly-CSharp.dll.v' is denied.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.Abstractions.FileWrapper.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Scarab.Services.Installer._InstallApi(ValueTuple`3 manifest) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 257
   at Scarab.Services.Installer.InstallApi() in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 228
   at Scarab.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 318
   at Scarab.Models.ModItem.OnInstall(IInstaller inst, Action`1 setProgress) in D:\a\Scarab\Scarab\Scarab\Models\ModItem.cs:line 211
   at Scarab.ViewModels.ModListViewModel.InternalModDownload(ModItem item, Func`3 downloader) in D:\a\Scarab\Scarab\Scarab\ViewModels\ModListViewModel.cs:line 812

**Comment by TheMulhima** [comment]
Привет, спасибо за ваш отчет. Ошибку, скорее всего, можно решить, запустив приложение скарабея от имени администратора (щелкните правой кнопкой мыши исполняемый файл и выберите «Запуск от имени администратора»). Ошибка возникает из-за того, что приложение не может получить доступ к файлам в папке с игрой, поэтому запуск от имени администратора должен решить проблему.
